CREATE TABLE client_registrations
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url      VARCHAR(255),
    name     VARCHAR(255),
    username VARCHAR(255),
    password VARCHAR(255),
    token    VARCHAR(255),
    CONSTRAINT pk_client_registrations PRIMARY KEY (id)
);

CREATE TABLE customers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number     VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE loans
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id  BIGINT,
    amount       DOUBLE PRECISION                        NOT NULL,
    status       VARCHAR(255),
    score        INTEGER                                 NOT NULL,
    limit_amount DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_loans PRIMARY KEY (id)
);

ALTER TABLE loans
    ADD CONSTRAINT FK_LOANS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);